version: '3'
services:
  sql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: XfmTicketing
      MYSQL_USER: xfm
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
